:global:
  componentName: cert-exporter
  githubUrl: https://github.com/projectsyn/component-cert-exporter
  feature_goldenTests: true

docs/antora.yml:
  name: cert-exporter
  title: cert-exporter
.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
